# 00. Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np

print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors
##Creating Tensors

pytorch tensors are created using torch.tensor()

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
t=torch.tensor([[[[[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]]]]])
t

tensor([[[[[ 1,  2,  3,  4],
           [ 5,  6,  7,  8],
           [ 9, 10, 11, 12]]]]])

In [17]:
t.ndim

5

In [18]:
t.shape

torch.Size([1, 1, 1, 3, 4])

### Random tensors

random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those numbers to
better represent the data


In [19]:
#create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1171, 0.2223, 0.2394, 0.7989],
        [0.4943, 0.7452, 0.2081, 0.0708],
        [0.6542, 0.3041, 0.5352, 0.3165]])

In [20]:
random_tensor.ndim

2

In [21]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))# height,width,color channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
#creating a range
l=torch.arange(0,10)
print(l)
i=torch.arange(0,100,10)
print(i)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [26]:
ten_zeros=torch.zeros_like(l)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [27]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

tensors not right datatype= tensor.dtype

tensor not right shape=tensor.shape

tensor not on right device=tensor.device

In [30]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1805, 0.6597, 0.4088, 0.6647],
        [0.7423, 0.2615, 0.4501, 0.6851],
        [0.6523, 0.3649, 0.3914, 0.4725]])

In [31]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1805, 0.6597, 0.4088, 0.6647],
        [0.7423, 0.2615, 0.4501, 0.6851],
        [0.6523, 0.3649, 0.3914, 0.4725]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors(Tensor Operations)

Addition

Subtraction

Multiplication

Division

Matrix Multiplication

In [32]:
tensor=torch.tensor([1,2,3])
tensor +10


tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
### Matrix Multiplication
#inner dimensions should be the same
#result takes the shape of the outer dimension
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
#finding the min,max,sum etc(tensor aggregation)

x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [38]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [40]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [41]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [42]:
#Find the positional min and max
x.argmin()

tensor(0)

In [43]:
x.argmax()

tensor(9)

#Reshaping, stacking, squeezing and unsqueezing tensors

Reshaping- reshapes an input tensor to a defined shape

View- return a view of an input tensor of certain shape but keep the same memory of the original tensor

Stacking- combine multiple tensors on top of each other(vstack) or side by side(hstack)

Squeeze- removes all '1' dimensions from a tensor

Unsqueeze- add a '1' dimension to a target tensor

Permute- return a view of the input with dimensions swapped in a certain way

In [44]:
x= torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [45]:
#add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [46]:
# change the view
z=x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [47]:
#changing z changes x
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [50]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
#squeeze and unsqueeze
x_reshaped.shape

torch.Size([1, 9])

In [53]:
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x_reshaped.squeeze().shape

torch.Size([9])

In [56]:
#permute
h=torch.randn(2,3,5)
h.shape

torch.Size([2, 3, 5])

In [58]:
torch.permute(h,(2,0,1)).shape

torch.Size([5, 2, 3])

###Indexing (Selecting data from Tensors)

In [59]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
x[0][0]

tensor([1, 2, 3])

In [62]:
x[0][0][0]

tensor(1)

###PyTorch and Numpy

In [63]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# PyTorch Reproducibility

#trying to take random out of random

In [67]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8695, 0.8985, 0.0882, 0.4945],
        [0.3255, 0.4998, 0.5160, 0.4953],
        [0.2651, 0.1176, 0.6472, 0.7839]])
tensor([[0.6032, 0.6498, 0.5857, 0.9173],
        [0.2793, 0.8215, 0.5044, 0.5077],
        [0.2620, 0.0585, 0.7453, 0.1907]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [69]:
#make a random but reproducible tensors

#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [70]:
import torch
torch.cuda.is_available()

False

In [72]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [73]:
###putting tensors and models on the GPU
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [74]:
###move tensor to gpu if available
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [75]:
###move tensors back to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])